[package]
name = "sse_clock"
version = "1.4.0"
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
ctrlc = "3.5.2"
log = { version = "0.4.34", features = ["std"] }
notify = { version = "8.2.0", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tray-item = "0.10.0"
ureq = { version = "3.4.2", features = ["json"], default-features = false }
windows = { version = "0.62.2", features = [
    "Win32_System_Console",
    "Win32_Foundation",
] }

[build-dependencies]
winresource = "0.1.31"
