name: Build

on:
  push:
    branches: [ "main_rust" ]
  pull_request:
    branches: [ "main_rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
